# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Francisco Alfaro Medina
site_url: https://github.com/fralfaro/portfolio
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/portfolio
repo_url: https://github.com/fralfaro/portfolio
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/neoteroi-mkdocs.css
  - assets/css/styles.css

# Theme
theme:
  name: dracula
  language: en
  logo: images/yo2.png
  favicon: images/logo_fam.png
  features:
    - content.tabs.link



# Plugins
plugins:
  - search

 #TOC
nav:
    - üè† Home: index.md
    - üëë About Me:
      - Presentation: about_me/me.md
      - Education:  about_me/education.md
      - Experience:  about_me/work_exp.md
      - More:  about_me/awards.md
    - üìñ Academics:
      - Research: research/research.md
      - Talks: research/talks.md
      - Students: research/students.md
      - Teaching: teaching/teaching.md
    - üöÄÔ∏è Portfolio:
      - Projects: software/projects.md
      - Documentation: software/book.md
      - Collaboration: software/collaboration.md
      - Resources: blog/extras.md





extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
      name: GitHub

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/francisco-alfaro/
      name: LinkedIn

    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=XXXX
      name: Google Scholar

    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0000-0000-0000
      name: ORCID

    - icon: fontawesome/solid/envelope
      link: mailto:francisco.alfaro@security.cl
      name: Email
